name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        sudo apt install libdbus-1-dev libbluetooth-dev -y
        cargo build --verbose
    - name: Test
      run: |
        sudo apt install libdbus-1-dev libbluetooth-dev -y
        cargo test --verbose
